version: "3.7"

# https://nodered.org/docs/getting-started/docker
services:
  node-red:
    image: nodered/node-red:latest
    hostname: "${ENV_TYPE}-nodered"
    environment:
      - TZ=Europe/Warsaw
    ports:
      - 1880:1880
    volumes:
      # it seems it doesn't work - `./volumes/node-red` is permanently empty
      - ./volumes/node-red:/data
    networks:
      iot-docker:
        ipv4_address: ${NODERED_IP}

  mosquitto:
    image: eclipse-mosquitto
    hostname: "${ENV_TYPE}-mosquitto"
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      iot-docker:
        ipv4_address: ${MOSQUITTO_IP}

  influxdb:
    image: influxdb:latest
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    networks:
      iot-docker:
        ipv4_address: ${INFLUXDB_IP}

  chronograf:
    image: chronograf:latest
    hostname: "${ENV_TYPE}-chronograf"
    volumes:
      - ./volumes/chronograf:/var/lib/chronograf
    ports:
      - 10000:10000
      - 8888:8888
    networks:
      iot-docker:
        ipv4_address: ${CHRONOGRAF_IP}

  telegraf:
    image: telegraf:latest
    hostname: "${ENV_TYPE}-telegram"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - 8092:8092/udp
      - 8094:8094
      - 8125:8125/udp
    networks:
      iot-docker:
        ipv4_address: ${TELEGRAF_IP}

  grafana:
    image: grafana/grafana:latest
    hostname: "${ENV_TYPE}-grafana"
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=$GF_INSTALL_PLUGINS
    volumes:
      # Data persistency
      # sudo mkdir -p ./volumes/grafana; chown 472:472 ./volumes/grafana/data
      - ./volumes/grafana:/var/lib/grafana
    networks:
      iot-docker:
        ipv4_address: ${GRAFANA_IP}

networks:
  iot-docker:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK}
