version: "3.7"

# https://nodered.org/docs/getting-started/docker
services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Europe/Warsaw
    ports:
      - 1880:1880
    volumes:
      # it seems it doesn't work - `./volumes/node-red` is permanently empty
      - ./volumes/node-red:/data
    networks:
      - localnet

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    # altough I expose 1883 node-red still returns error:
    # "Connection failed to broker: mqtt://localhost:1883"
    expose:
      - 1883
      - 9001
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - localnet

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    networks:
      - localnet

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    volumes:
      - ./volumes/chronograf:/var/lib/chronograf
    ports:
      - 10000:10000
      - 8888:8888
    links:
      - influxdb
    networks:
      - localnet

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    links:
      - influxdb
    ports:
      - 8092:8092/udp
      - 8094:8094
      - 8125:8125/udp
    networks:
      - localnet

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    env_file:
      - "env.grafana"
    user: "0"
    links:
      - influxdb
    volumes:
      # Data persistency
      # sudo mkdir -p ./volumes/grafana; chown 472:472 ./volumes/grafana/data
      - ./volumes/grafana:/var/lib/grafana
    networks:
      - localnet

networks:
  localnet:
    name: localnet
